export const nummerDrieSchema = [
  {
    "identifier": "EFGHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3F",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "DFGHIJKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3I",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "DEGHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3D",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "DEFHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "DEFGIJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "DEFGHJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "DEFGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "DEFGHIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "DEFGHIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "CFGHIJKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CEGHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CEFHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CEFGIJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CEFGHJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CEFGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CEFGHIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "CEFGHIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "CDGHIJKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDFHIJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3I",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDFGIJKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3I",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDFGHJKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDFGHIKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3I",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDFGHIJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "CDFGHIJK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "CDEHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEGIJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEGHJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEGHIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "CDEGHIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "CDEFIJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEFHJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEFHIKL",
    "WA": "3C",
    "WB": "3E",
    "WD": "3I",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEFHIJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "CDEFHIJK",
    "WA": "3C",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "CDEFGJKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEFGIKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEFGIJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "CDEFGIJK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "CDEFGHKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "CDEFGHJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "CDEFGHJK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "CDEFGHIL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "CDEFGHIK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "CDEFGHIJ",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "BFGHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3I",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BEGHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3B",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BEFHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3I",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BEFGIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3I",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BEFGHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BEFGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3F",
    "WG": "3I",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BEFGHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BEFGHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3H",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BDGHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDFHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDFGIJKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDFGHJKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDFGHIKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDFGHIJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BDFGHIJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BDEHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEGIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEGHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEGHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BDEGHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BDEFIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEFHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEFHIKL",
    "WA": "3E",
    "WB": "3I",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEFHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BDEFHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BDEFGJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEFGIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEFGIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BDEFGIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BDEFGHKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BDEFGHJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "BDEFGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "BDEFGHIL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BDEFGHIK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BDEFGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "BCGHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCFHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCFGIJKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCFGHJKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCFGHIKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCFGHIJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCFGHIJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCEHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEGIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEGHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEGHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCEGHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCEFIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEFHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEFHIKL",
    "WA": "3E",
    "WB": "3I",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEFHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCEFHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCEFGJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEFGIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEFGIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCEFGIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCEFGHKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCEFGHJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "BCEFGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "BCEFGHIL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCEFGHIK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCEFGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "BCDHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDGIJKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDGHJKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDGHIKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDGHIJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDGHIJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDFIJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDFHJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDFHIKL",
    "WA": "3C",
    "WB": "3I",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDFHIJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDFHIJK",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDFGJKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDFGIKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDFGIJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDFGIJK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDFGHKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDFGHJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3J"
  },
  {
    "identifier": "BCDFGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3D",
    "WL": "3K"
  },
  {
    "identifier": "BCDFGHIL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDFGHIK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDFGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3D",
    "WL": "3I"
  },
  {
    "identifier": "BCDEIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEHIKL",
    "WA": "3E",
    "WB": "3I",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDEHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDEGJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEGIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3I",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEGIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDEGIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDEGHKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEGHJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "BCDEGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "BCDEGHIL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDEGHIK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3H",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDEGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3D",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "BCDEFJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3E",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFIKL",
    "WA": "3C",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFIJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3E",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDEFIJK",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3E",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFHKL",
    "WA": "3C",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFHJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "BCDEFHJK",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFHIL",
    "WA": "3C",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDEFHIK",
    "WA": "3C",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFHIJ",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "BCDEFGKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3E",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFGJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "BCDEFGJK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFGIL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3E",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "BCDEFGIK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3E",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFGIJ",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3J",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "BCDEFGHL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "BCDEFGHK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "BCDEFGHJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3J",
    "WI": "3F",
    "WK": "3D",
    "WL": "3E"
  },
  {
    "identifier": "BCDEFGHI",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3H",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "AFGHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3I",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "AEGHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3A",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "AEFHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "AEFGIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "AEFGHJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "AEFGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "AEFGHIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "AEFGHIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ADGHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADFHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADFGIJKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADFGHJKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADFGHIKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADFGHIJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ADFGHIJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ADEHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEGIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEGHJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEGHIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ADEGHIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ADEFIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEFHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEFHIKL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEFHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ADEFHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ADEFGJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEFGIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEFGIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ADEFGIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ADEFGHKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ADEFGHJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ADEFGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ADEFGHIL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ADEFGHIK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ADEFGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ACGHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACFHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACFGIJKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACFGHJKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACFGHIKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACFGHIJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACFGHIJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACEHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEGIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEGHJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEGHIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACEGHIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACEFIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEFHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEFHIKL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEFHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACEFHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACEFGJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEFGIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEFGIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACEFGIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACEFGHKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACEFGHJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ACEFGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ACEFGHIL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACEFGHIK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACEFGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ACDHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDGIJKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDGHJKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDGHIKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDGHIJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDGHIJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDFIJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDFHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDFHIKL",
    "WA": "3H",
    "WB": "3F",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDFHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDFHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDFGJKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDFGIKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDFGIJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDFGIJK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDFGHKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDFGHJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3H"
  },
  {
    "identifier": "ACDFGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3K"
  },
  {
    "identifier": "ACDFGHIL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDFGHIK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDFGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3I"
  },
  {
    "identifier": "ACDEIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEHIKL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDEHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDEGJKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEGIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3I",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEGIJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDEGIJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDEGHKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEGHJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ACDEGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ACDEGHIL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDEGHIK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDEGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ACDEFJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFIKL",
    "WA": "3C",
    "WB": "3E",
    "WD": "3I",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFIJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDEFIJK",
    "WA": "3C",
    "WB": "3J",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFHKL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFHJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ACDEFHJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFHIL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDEFHIK",
    "WA": "3H",
    "WB": "3E",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFHIJ",
    "WA": "3H",
    "WB": "3J",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3I"
  },
  {
    "identifier": "ACDEFGKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFGJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ACDEFGJK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFGIL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ACDEFGIK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3E",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFGIJ",
    "WA": "3C",
    "WB": "3G",
    "WD": "3J",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ACDEFGHL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3F",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ACDEFGHK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3K"
  },
  {
    "identifier": "ACDEFGHJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3J",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3E"
  },
  {
    "identifier": "ACDEFGHI",
    "WA": "3H",
    "WB": "3G",
    "WD": "3E",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3I"
  },
  {
    "identifier": "ABGHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABFHIJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABFGIJKL",
    "WA": "3I",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABFGHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABFGHIKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABFGHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABFGHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABEHIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEGIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEGHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEGHIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEGHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3H",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABEGHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3H",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABEFIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEFHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEFHIKL",
    "WA": "3E",
    "WB": "3I",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEFHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABEFHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABEFGJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEFGIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEFGIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABEFGIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABEFGHKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABEFGHJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABEFGHJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABEFGHIL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABEFGHIK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3H",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABEFGHIJ",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABDHIJKL",
    "WA": "3I",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDGIJKL",
    "WA": "3I",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDGHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDGHIKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDGHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDGHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDFIJKL",
    "WA": "3I",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDFHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDFHIKL",
    "WA": "3H",
    "WB": "3I",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDFHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDFHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDFGJKL",
    "WA": "3F",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDFGIKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDFGIJL",
    "WA": "3F",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDFGIJK",
    "WA": "3F",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDFGHKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDFGHJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3J"
  },
  {
    "identifier": "ABDFGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3J",
    "WL": "3K"
  },
  {
    "identifier": "ABDFGHIL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDFGHIK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDFGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3J"
  },
  {
    "identifier": "ABDEIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEHIKL",
    "WA": "3E",
    "WB": "3I",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDEHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDEGJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEGIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEGIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDEGIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDEGHKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEGHJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABDEGHJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABDEGHIL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDEGHIK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3H",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDEGHIJ",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABDEFJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFIKL",
    "WA": "3E",
    "WB": "3I",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDEFIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFHKL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFHJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABDEFHJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFHIL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDEFHIK",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFHIJ",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABDEFGKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFGJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3J"
  },
  {
    "identifier": "ABDEFGJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3J",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFGIL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABDEFGIK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFGIJ",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3J"
  },
  {
    "identifier": "ABDEFGHL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABDEFGHK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABDEFGHJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3J"
  },
  {
    "identifier": "ABDEFGHI",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABCHIJKL",
    "WA": "3I",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCGIJKL",
    "WA": "3I",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCGHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCGHIKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCGHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCGHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCFIJKL",
    "WA": "3I",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCFHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCFHIKL",
    "WA": "3H",
    "WB": "3I",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCFHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCFHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCFGJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCFGIKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCFGIJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCFGIJK",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3F",
    "WG": "3A",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCFGHKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCFGHJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3J"
  },
  {
    "identifier": "ABCFGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3J",
    "WL": "3K"
  },
  {
    "identifier": "ABCFGHIL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCFGHIK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCFGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3J"
  },
  {
    "identifier": "ABCEIJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3C",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEHJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEHIKL",
    "WA": "3E",
    "WB": "3I",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEHIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCEHIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCEGJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEGIKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3A",
    "WG": "3I",
    "WI": "3C",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEGIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCEGIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCEGHKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEGHJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABCEGHJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABCEGHIL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCEGHIK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3H",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCEGHIJ",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3G",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABCEFJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFIKL",
    "WA": "3E",
    "WB": "3I",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCEFIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFHKL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFHJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABCEFHJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFHIL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCEFHIK",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFHIJ",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABCEFGKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFGJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3J"
  },
  {
    "identifier": "ABCEFGJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3J",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFGIL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCEFGIK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFGIJ",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3J"
  },
  {
    "identifier": "ABCEFGHL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABCEFGHK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABCEFGHJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3J"
  },
  {
    "identifier": "ABCEFGHI",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABCDIJKL",
    "WA": "3I",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDHJKL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDHIKL",
    "WA": "3H",
    "WB": "3I",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDHIJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDHIJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDGJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDGIKL",
    "WA": "3I",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDGIJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDGIJK",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3G",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDGHKL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDGHJL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3J"
  },
  {
    "identifier": "ABCDGHJK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3J",
    "WL": "3K"
  },
  {
    "identifier": "ABCDGHIL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDGHIK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDGHIJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3J"
  },
  {
    "identifier": "ABCDFJKL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFIKL",
    "WA": "3C",
    "WB": "3I",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFIJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDFIJK",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFHKL",
    "WA": "3H",
    "WB": "3F",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFHJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3H"
  },
  {
    "identifier": "ABCDFHJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFHIL",
    "WA": "3H",
    "WB": "3F",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDFHIK",
    "WA": "3H",
    "WB": "3F",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFHIJ",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3I"
  },
  {
    "identifier": "ABCDFGKL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFGJL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3J"
  },
  {
    "identifier": "ABCDFGJK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3J",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFGIL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDFGIK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFGIJ",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3J"
  },
  {
    "identifier": "ABCDFGHL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3H"
  },
  {
    "identifier": "ABCDFGHK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3K"
  },
  {
    "identifier": "ABCDFGHJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3J"
  },
  {
    "identifier": "ABCDFGHI",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEJKL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEIKL",
    "WA": "3E",
    "WB": "3I",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEIJL",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEIJK",
    "WA": "3E",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEHKL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEHJL",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABCDEHJK",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEHIL",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEHIK",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEHIJ",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEGKL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEGJL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3J"
  },
  {
    "identifier": "ABCDEGJK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3J",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEGIL",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEGIK",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEGIJ",
    "WA": "3E",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3I",
    "WL": "3J"
  },
  {
    "identifier": "ABCDEGHL",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABCDEGHK",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEGHJ",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3E",
    "WL": "3J"
  },
  {
    "identifier": "ABCDEGHI",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEFKL",
    "WA": "3C",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEFJL",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABCDEFJK",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEFIL",
    "WA": "3C",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEFIK",
    "WA": "3C",
    "WB": "3E",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3I",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEFIJ",
    "WA": "3C",
    "WB": "3J",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEFHL",
    "WA": "3H",
    "WB": "3F",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3D",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABCDEFHK",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEFHJ",
    "WA": "3H",
    "WB": "3J",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3E"
  },
  {
    "identifier": "ABCDEFHI",
    "WA": "3H",
    "WB": "3E",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEFGL",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3L",
    "WL": "3E"
  },
  {
    "identifier": "ABCDEFGK",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3K"
  },
  {
    "identifier": "ABCDEFGJ",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3J"
  },
  {
    "identifier": "ABCDEFGI",
    "WA": "3C",
    "WB": "3G",
    "WD": "3B",
    "WE": "3D",
    "WG": "3A",
    "WI": "3F",
    "WK": "3E",
    "WL": "3I"
  },
  {
    "identifier": "ABCDEFGH",
    "WA": "3H",
    "WB": "3G",
    "WD": "3B",
    "WE": "3C",
    "WG": "3A",
    "WI": "3F",
    "WK": "3D",
    "WL": "3E"
  }
]